// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AgentResponse {
    message: string;
    toolCalls?: ToolCallInfo[];
}

export interface ToolCallInfo {
    tool: string;
    detail: string;
}

export interface Session {
    id: string;
    title: string;
    createdAt: string;
}

export interface Settings {
    notifications: boolean;
    modelMode: string;
    theme: string;
}

export function SendMessage(arg1: string, arg2: string): Promise<AgentResponse>;
export function GetSessions(): Promise<Session[]>;
export function GetPersona(): Promise<string>;
export function SavePersona(arg1: string): Promise<void>;
export function GetSettings(): Promise<Settings>;
export function SaveSettings(arg1: Settings): Promise<void>;
