// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetPersona():Promise<string>;

export function GetSessions():Promise<Array<main.Session>>;

export function GetSettings():Promise<main.Settings>;

export function SavePersona(arg1:string):Promise<void>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function SendMessage(arg1:string,arg2:string):Promise<main.AgentResponse>;
